nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'token', 'shop-token']
        expose_headers: ['Link', 'token', 'shop-token']
        max_age: 3600
    paths:
        '^/': null
